Updated input handling to fix ImGui.Net breaking changes.
NogginBops/ImGui.NET_OpenTK_Sample pull request #29
Opened 2023-11-21 22:52 UTC by NoahGWood

Fixed errors caused by changes in latest [ImGuiNet](https://github.com/ImGuiNET/ImGui.NET/issues/451) * enabled support for docking.

2023-11-22 14:57 UTC, NogginBops requested changes
Thanks a lot for the PR!

A goal with this repo is to make `ImGuiController.cs` useable standalone by just copying the file, this means that the `KeyTranslator.cs` should be part of the `UpdateImGuiInput()` method (it's fine if the method becomes really long).

2023-11-23 23:34 UTC, NoahGWood commented
Should be fixed :)

2023-11-25 04:05 UTC, zaafar commented on Dear ImGui Sample/ImGuiController.cs
> +            switch (key)
[optional] you can reduce the length a bit if you do something like this.
https://github.com/zaafar/ClickableTransparentOverlay/blob/master/ClickableTransparentOverlay/ImGuiInputHandler.cs#L161:L172

2023-12-13 10:11 UTC, NogginBops approved these changes

2023-12-13 10:11 UTC, merged